config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, controllers: {sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "callbacks"}

  root to: "home#index"

  resources :users do
    resources :follows, only: :create
  end

  resources :topics do
    resources :fotopics, only: :create
  end

  resources :answers do
    resources :votes
    resources :verans
    resources :hisans
  end

  resources :verans

  resources :questions do
    resources :verques, :protques
    resources :comments, only: :show
    resources :requests
    resources :searchs, only: :index
    resources :hisques, only: :index
  end

  resources :verques do
  end

  resources :notifies

  resources :comments do
    resources :votes
  end

  namespace :admin do
    root "home#index", path: "/"
    resources :users
    resources :topics
    resources :questions
  end

  resources :chats

  namespace :api do
    root "home#index", path: "/"
    resources :topics do
      get "list_user_follow", path: "users"
      get "push", path: "messages"
    end
  end

  get "noti", to: "requests#test"

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :question_topics, dependent: :destroy
  has_many :questions, through: :question_topics

  has_many :actions, as: :actionable

  validates :name, presence: true, length: {maximum: Settings.topic.name_max}
  validates :description, presence: true, length: {maximum: Settings.topic.description_max}
  validates :icon, presence: true

  mount_uploader :icon, IconTopicUploader

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  scope :topics_login_user, -> user_id do
    joins(:actions).where(actions: {actionable_type: Action.target_acts[:topic],
      type_act: Action.type_acts[:follow], user_id: user_id})
  end

  class << self
    include Common
    
    def is_follow current_user_id, topic_id
      query = Action.by_user(current_user_id).target(Action.target_acts[:topic])
        .with_id(topic_id).is_follow
      query.length != 0
    end

    def find_muti id
      topic = Topic.find_by slug: id
      unless topic
        topic = Topic.find_by id: id
        if topic
          return topic
        else
          return false
        end   
      else
        return topic  
      end
    end
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < AdminController

  def index
    @topics = Topic.page(params[:page]).per Settings.admin.per_page
    respond_to do |format|
      format.html
      format.csv {send_data @topics.to_csv}
    end
  end

  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.find_by id: params[:id]
    unless @topic
      flash[:danger] = t "flash.admin.topic.not_found"
      redirect_to admin_topics_path
    end
  end

  def update
    @topic = Topic.find_by slug: params[:id]
    unless @topic
      flash[:danger] = t "flash.admin.topic.not_found"
      redirect_to admin_topics_path
    end
    if @topic.update_attributes topic_params
      flash[:success] = t "flash.admin.topic.update.success"
      redirect_to admin_topics_path
    else
      flash[:danger] = t "flash.admin.topic.update.failed"
      render :edit
    end
  end

  def destroy
    @topic = Topic.find_by id: params[:id]
    @topic.questions.destroy_all
    @topic = Topic.destroy params[:id]
    if @topic.destroyed?
      flash[:success] = t "flash.admin.topic.delete.success"
      redirect_to admin_topics_path
    else
      flash[:danger] = t "flash.admin.topic.delete.failed"
      redirect_to :back
    end
  end

  def create
    @topic = Topic.new topic_params
    if @topic.save
      redirect_to admin_topics_path
    else
      redirect_to :back
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:icon, :name, :description)
  end
end

app/controllers/api/topics_controller.rb
class Api::TopicsController < ApplicationController

  def list_user_follow
    @users = User.with_topic params[:topic_id]
    render json: @users
  end

  def push
    redis = Redis.new(host: "127.0.0.1", port: 6379)
    message = ActiveSupport::JSON.encode({ name: 'ngoc11', id: 11,
      avatar: "http://lorempixel.com/40/40/", content: "hello", time: Time.now.to_i })

    addObj = redis.zadd("topic_#{params[:topic_id]}", Time.now.to_i, message)

    messages = redis.zrange("topic_#{params[:topic_id]}", 0, -1, :with_scores => true)

    ChatChannel.receive(messages)
    render text: messages
  end

  private

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  layout "main"

  def index
  end

  def new
    @topic = Topic.new
  end

  def show
    @topic = Topic.includes({questions: [:topics, :user,
      answers: [:user, {comments: [:actions, :user]}]]}).find_muti params[:id]
    if @topic
      @questions = @topic.questions.page(params[:page])
        .per Settings.topic.per_page
      if user_signed_in?
        @isFollow = Topic.is_follow(current_user.id, @topic.id)
      end
      @countQuestion = @topic.questions.count
      @numberPeopleFollow = Action.numberFollow(@topic.id).distinct.count(:user_id)
      @numberAnswerInTopic = Answer.numberAnwserInTopic(@topic.id).distinct.count
    else
      redirect_to root_path;
    end
  end

end

app/views/admin/topics/_list.html.erb
<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.name %></td>
    <td><%= topic.description %></td>
    <td><img src="<%= asset_path(topic.icon) %>" class="img_25" />
    </td>
    <td>
      <a href="<%= admin_topic_path(topic.id) %>"
         data-method="delete" rel="nofollow">
        <i class="fa fa-times" aria-hidden="true"></i></a>
      <a href="<%= edit_admin_topic_path(topic.id) %>">
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
    </td>
  </tr>
<% end %>

app/views/admin/topics/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <%= t("admin.topic.edit.title") %>
    <small><%= t("admin.topic.edit.sub_title") %></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_topics_path %>"><i class="fa fa-dashboard"></i>
      <%= t("admin.topic.list.title") %></a></li>
    <li class="active"><%= t("admin.topic.edit.title") %></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <!-- /.content -->
  <%= simple_form_for [:admin, @topic] do |f| %>
    <%= f.input :name, autofocus: true %>
    <%= f.input :description, as: :text, autofocus: true %>
    <%= f.input :icon, as: :file %>
    <div class="form-img-preview">
      <img src="<%= @topic.icon %>" alt="" class="img_40">
    </div>
    <div class="actions">
      <%= f.button :submit, value: "Save" %>
    </div>
  <% end %>
</section>

app/views/admin/topics/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <%= t "admin.topic.list.title" %>
    <small><%= t "admin.topic.list.sub_title" %></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_path %>"><i class="fa fa-dashboard"></i> 
      <%= t "admin.home" %></a></li>
    <li class="active"><%= t "admin.topic.list.title" %></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <%= link_to t("admin.user.list.btn_export_csv"), 
    admin_topics_path(format: :csv), class: "btn btn-primary" %>
  <table id="list-topics" class="table table-striped table-bordered" 
    cellspacing="0" width="100%">
    <thead>
      <tr>
        <th><%= t "admin.topic.list.name" %></th>
        <th><%= t "admin.topic.list.description" %></th>
        <th><%= t "admin.topic.list.icon" %></th>
        <th><%= t "admin.topic.list.action" %></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th><%= t "admin.topic.list.name" %></th>
        <th><%= t "admin.topic.list.description" %></th>
        <th><%= t "admin.topic.list.icon" %></th>
        <th><%= t "admin.topic.list.action" %></th>
      </tr>
    </tfoot>
    <tbody>
      <%= render "list" %>
    </tbody>
  </table>
  <%= paginate @topics %>
</section>
<!-- /.content -->

app/views/admin/topics/new.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <%= t("admin.topic.new.title") %>
    <small><%= t("admin.topic.new.sub_title") %></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_topics_path %>"><i class="fa fa-dashboard"></i><%= t("admin.topic.list.title") %></a></li>
    <li class="active"><%= t("admin.topic.new.title") %></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <!-- /.content -->
  <%= simple_form_for [:admin, @topic] do |f| %>
    <%= f.input :name, autofocus: true %>
    <%= f.input :description, as: :text, autofocus: true %>
    <%= f.input :icon, as: :file %>
    <div class="actions">
      <%= f.button :submit, value: "Save" %>
    </div>
  <% end %>
</section>