config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, controllers: {sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "callbacks"}

  root to: "home#index"

  resources :users do
    resources :follows, only: :create
  end

  resources :topics do
    resources :fotopics, only: :create
  end

  resources :answers do
    resources :votes
    resources :verans
    resources :hisans
  end

  resources :verans

  resources :questions do
    resources :verques, :protques
    resources :comments, only: :show
    resources :requests
    resources :searchs, only: :index
    resources :hisques, only: :index
  end

  resources :verques do
  end

  resources :notifies

  resources :comments do
    resources :votes
  end

  namespace :admin do
    root "home#index", path: "/"
    resources :users
    resources :topics
    resources :questions
  end

  resources :chats

  namespace :api do
    root "home#index", path: "/"
    resources :topics do
      get "list_user_follow", path: "users"
      get "push", path: "messages"
    end
  end

  get "noti", to: "requests#test"

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController

  def index
  end

  def show
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "main"

  def index
    @topics = Topic.all
    if params.has_key? :word_search
      @q = Question.ransack(title_or_content_cont: params[:word_search])
      @questions = @q.result.includes([:topics, :user, :actions])
        .page(params[:page]).per Settings.home.per_page
      render template: "home/search"
    else
      if user_signed_in?
        @questions = Kaminari.paginate_array(Question.new_feed_login(current_user.id))
          .page(params[:page]).per Settings.home.per_page
        @topicsFollow = Topic.topics_login_user current_user.id
      else
        @questions = Question.includes([:topics, :user, :actions])
          .page(params[:page]).per Settings.home.per_page
      end
    end
  end
end

app/views/home/index.html.erb
<section id="home-page">
  <div class="feed-wrap row">
    <% if user_signed_in? %>
      <div class="sidebar-topic-trending col-md-3">
        <%= react_component("HomeListTopic", topicsFollow: @topicsFollow,
          topics: @topics) %>
      </div>
    <% end %>
    <div class="feed-inner-wrap col-md-9">
      <span class="home_main_feed_head">
        <%= t "home_page.top_question_for_you" %></span>

      <% if user_signed_in? %>
        <div class="feed_suggest_ask">
          <div class="user-info">
            <div class="wr-avatar">
              <img src="<%= current_user.avatar.url %>" alt=""
                class="circle img img_30">
            </div>
            <span class="name"><%= current_user.name %></span>
          </div> <!-- .user-info -->
          <div class="wr-suggest-ask">
          <%= link_to t("home_page.sentence_suggest_ask"), new_question_path,
            class: "sentence-suggest-ask" %>
          </div>
        </div> <!-- .feed_suggest_ask -->
      <% end %>

      <div class="question-feed">
        <% @questions.each do |question| %>
          <div class="paged-list-item">
            <div class="feed-item-inner">
              <div class="list-topics">
                <% question.topics.each do |topic| %>
                  <span class="item-topic">
                    <%= link_to topic.name, topic_path(topic.slug) %>
                  </span>
                <% end %>
              </div>
              <span class="feed-ques-title">
                <%= link_to question.title, question_path(question.slug),
                  alt: question.title %>
              </span>
              <span class="author">
                <div class="wr-avatar">
                  <%= image_tag question.user.avatar.url,
                    class: "circle img_40" %>
                </div>
                <div class="name">
                  <%= question.user.name %>
                </div>
              </span>
              <div class="time">
                <%= question.updated_at %>
              </div>
              <div class="ques-content marked">
                <%= question.content %>
              </div>
            </div>
          </div> <!-- .paged-list-item -->
        <% end %>

        <%= paginate @questions %>
      </div> <!-- .question-feed -->
    </div>
  </div>
</section>

app/views/home/search.html.erb
<section id="home-page">
  <div class="feed-wrap row">
    <div class="feed-inner-wrap col-md-9">
      <span class="home_main_feed_head">
        <strong><%= t "search_page.title" %>
          <% if params[:word_search].present? %>
            <%= params[:word_search] %>
          <% end %>
        </strong>
      </span>

      <div class="question-feed">
        <% @questions.each do |question| %>
          <div class="paged-list-item">
            <div class="feed-item-inner">
              <div class="list-topics">
                <% question.topics.each do |topic| %>
                  <span class="item-topic">
                    <%= link_to topic.name, topic_path(topic.slug),
                      alt: topic.name %>
                  </span>
                <% end %>
              </div>
              <div class="time">
                <%= question.updated_at %>
              </div>
              <span class="feed-ques-title">
                <%= link_to question.title, question_path(question.slug),
                  alt: question.title %>
              </span>
              <span class="author">
                <div class="wr-avatar">
                  <%= image_tag question.user.avatar.url,
                    class: "circle img_40" %>
                </div>
                <div class="name">
                  <%= question.user.name %>
                </div>
              </span>
              <div class="ques-content">
                <%= raw question.content %>
              </div>
            </div>
          </div> <!-- .paged-list-item -->
        <% end %>

        <%= will_paginate @questions %>

      </div> <!-- .question-feed -->
    </div>
  </div>
</section>