config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, controllers: {sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "callbacks"}

  root to: "home#index"

  resources :users do
    resources :follows, only: :create
  end

  resources :topics do
    resources :fotopics, only: :create
  end

  resources :answers do
    resources :votes
    resources :verans
    resources :hisans
  end

  resources :verans

  resources :questions do
    resources :verques, :protques
    resources :comments, only: :show
    resources :requests
    resources :searchs, only: :index
    resources :hisques, only: :index
  end

  resources :verques do
  end

  resources :notifies

  resources :comments do
    resources :votes
  end

  namespace :admin do
    root "home#index", path: "/"
    resources :users
    resources :topics
    resources :questions
  end

  resources :chats

  namespace :api do
    root "home#index", path: "/"
    resources :topics do
      get "list_user_follow", path: "users"
      get "push", path: "messages"
    end
  end

  get "noti", to: "requests#test"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable
  
  include PublicActivity::Model
  has_many :activities, as: :trackable, class_name: "PublicActivity::Activity", 
    dependent: :destroy
  
  has_many :actions
  has_many :questions
  has_many :answers
  has_many :comments

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  before_save :init_role
  before_validation :init_role
  
  mount_uploader :avatar, AvatarUploader
  enum role: [:admin, :user, :moderator]

  validates :name, presence: true, length: {maximum: Settings.user[:name_max]}
  validates :story, length: {maximum: Settings.user[:story_max]}
  validates :email, presence: true, length: {maximum: Settings.user[:email_max]}
  validates :role, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, 
    message: I18n.t("flash.user.email")

  scope :with_topic, -> topic_id do
    joins(:actions).where(actions: {actionable_type: Action.target_acts[:topic],
      type_act: Action.type_acts[:follow], actionable_id: topic_id})
  end

  class << self

    def is_follow_user(user_id, current_user_id)
      query = Action.where "user_id = ? and actionable_type = ? and actionable_id = ? and type_act = ?",
        current_user_id, "User", user_id, Action.type_acts[:follow];
      return query.length != 0
    end

    def number_user_follow user_id
      query = Action.where "actionable_type = ? and actionable_id = ? and type_act = ?",
        Action.target_acts[:user], user_id, Action.type_acts[:follow];
      return query.length
    end

    def is_upvote_answer(current_user_id, answer_id)
      query = Action.is_upvote_answer current_user_id, answer_id
      return query.length != 0
    end

    def is_downvote_answer(current_user_id, answer_id)
      query = Action.is_downvote_answer current_user_id, answer_id;
      return query.length != 0
    end

    def is_upvote_question(current_user_id, question_id)
      query = Action.is_upvote_question current_user_id, question_id;
      return query.length != 0
    end

    def is_downvote_question(current_user_id, question_id)
      query = Action.is_downvote_question current_user_id, question_id;
      return query.length != 0
    end
    
    def remove_upvote_question current_user_id, question_id
      query = Action.where "user_id = ? and actionable_type = ? and actionable_id = ? and type_act = ?",
        current_user_id, Action.target_acts[:question], question_id, Action.type_acts[:up_vote];
      query.destroy_all
    end

    def remove_downvote_question current_user_id, question_id
      query = Action.where "user_id = ? and actionable_type = ? and actionable_id = ? and type_act = ?",
        current_user_id, Action.target_acts[:question], question_id, Action.type_acts[:down_vote];
      query.destroy_all
    end

    def remove_upvote_answer current_user_id, answer_id
      query = Action.where "user_id = ? and actionable_type = ? and actionable_id = ? and type_act = ?",
        current_user_id, Action.target_acts[:answer], answer_id, Action.type_acts[:up_vote];
      query.destroy_all
    end

    def remove_downvote_answer current_user_id, answer_id
      query = Action.where "user_id = ? and actionable_type = ? and actionable_id = ? and type_act = ?",
        current_user_id, Action.target_acts[:answer], answer_id, Action.type_acts[:down_vote];
      query.destroy_all
    end

    def activity_by_user user_id
      PublicActivity::Activity.order("created_at desc")
        .where owner_id: user_id
    end

    def from_omniauth auth
      @users = where(provider: auth.provider, uid: auth.uid)
      if @users.length == 0
        @user = User.new
        @user.provider = auth.provider
        @user.uid = auth.uid
        @user.email = auth.info.email
        @user.name = auth.info.name
        @user.remote_avatar_url = auth.info.image.gsub("http://", "https://")
        @user.password = Devise.friendly_token[0, 20]
        @user.role = User.roles[:user]
        @user.save!
        @user
      else
        @users.first
      end
    end

    include Common
  end

  private

  def init_role
    self.role ||= :user
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @users = User.page(params[:page]).per Settings.admin.per_page;
    respond_to do |format|
      format.html
      format.csv {
        send_data @users.to_csv
      }
    end
  end

  def edit
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "flash.admin.user.not_found"
      redirect_to admin_topics_path
    end
  end

  def update
    @user = User.find_by slug: params[:id]
    unless @user
      flash[:danger] = t "flash.admin.user.not_found"
      redirect_to admin_topics_path
    end
    if @user.update_attributes user_params
      flash[:success] = t "flash.admin.user.update.success"
      redirect_to admin_users_path
    else
      flash[:danger] = t "flash.admin.user.update.failed"
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit :name, :email, :story, :avatar, :role
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  layout "main"

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name, :avatar, :story])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :name, :avatar, :story])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  prepend_before_filter :verify_signed_out_user, only: :destroy

  layout "main"

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    cookies.delete(:auth_token)
    reset_session
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "main"
  respond_to :json, :html

  def index
  end

  def show
    @user = User.includes([:actions, :questions, {answers: :question}, :comments])
      .find_by id: params[:id]
    unless @user
      flash[:danger] = t "flash.user.not_found"
      redirect_to root_path
    end
    @support = Supports::UserSupport.new(@user)
    @activities = User.activity_by_user(params[:id])
      .page(params[:page])
      .per(Settings.profile.activity.per_page)

    if user_signed_in?
      @isFollowUser = User.is_follow_user(params[:id], current_user.id)
    end
  end
end

app/views/admin/users/_list.html.erb
<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.story %></td>
    <td><img src="<%= asset_path(user.avatar) %>" class="img_25" /></td>
    <td><%= user.created_at %></td>
    <td><%= user.role %></td>
    <td>
      <a href="<%= edit_admin_user_path(user.id) %>">
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
    </td>
  </tr>
<% end %>

app/views/admin/users/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <%= t("admin.user.edit.title") %>
    <small><%= t("admin.user.edit.sub_title") %></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_users_path %>"><i class="fa fa-dashboard"></i>
      <%= t("admin.user.list.title") %></a></li>
    <li class="active"><%= t("admin.user.edit.title") %></li>
  </ol>
</section>

<section class="content">
  <%= simple_form_for [:admin, @user] do |f| %>
    <%= f.input :name, autofocus: true %>
    <%= f.input :story, as: :text, autofocus: true %>
    <%= f.input :email, autofocus: true %>
    <%= f.input :avatar, as: :file %>
    <div class="form-img-preview">
      <%= image_tag @user.avatar, class: "img_40" %>
    </div>
    <div class="form-group">
      <label for="user[role]"><%= t("admin.user.edit.role") %></label>
      <%= f.select(:role, User::roles.keys.map {|role| [role.titleize, role]},
        {}, {class: "form-control"}) %>
    </div>
    <div class="actions">
      <%= f.button :submit, value: t("admin.user.edit.save") %>
    </div>
  <% end %>
</section>

app/views/admin/users/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <%= t("admin.user.list.title") %>
    <small><%= t("admin.user.list.sub_title") %></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= admin_path %>"><i class="fa fa-dashboard"></i>
      <%= t("admin.home") %></a></li>
    <li class="active"><%= t("admin.user.list.title") %></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="control">
    <%= link_to t("admin.user.list.btn_export_csv"), 
      admin_topics_path(format: :csv), class: "btn btn-primary" %>
  </div>
	<table id="list-users" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th><%= t("admin.user.list.name") %></th>
        <th><%= t("admin.user.list.email") %></th>
        <th><%= t("admin.user.list.story") %></th>
        <th><%= t("admin.user.list.avatar") %></th>
        <th><%= t("admin.user.list.register_date") %></th>
        <th><%= t("admin.user.list.role") %></th>
        <th><%= t("admin.user.list.action") %></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th><%= t("admin.user.list.name") %></th>
        <th><%= t("admin.user.list.email") %></th>
        <th><%= t("admin.user.list.story") %></th>
        <th><%= t("admin.user.list.avatar") %></th>
        <th><%= t("admin.user.list.register_date") %></th>
        <th><%= t("admin.user.list.role") %></th>
        <th><%= t("admin.user.list.action") %></th>
      </tr>
    </tfoot>
    <tbody>
        <%= render "_list" %>
    </tbody>
  </table>
  <%= paginate @users %>
</section>
<!-- /.content -->